### Exception
* 파이썬에서 모든 에러는 `BaseException`의 서브클래스다
* 또 하위 클래스 중 Exception이 존재하며, 시스템 관련 내장 예외는 모두 이 클래스를 상속받고 있는데, 사용자 정의 에러는 이 에러를 상속하기를 권장하고 있다
* 에러를 핸들링하는 문법은 다음과 같은데,
  ```python
    try:
      someFunction()
    except LightError as error:
      print(error)
    except HeavyError as error:
      print(error)
      raise CriticalError from error
    else:
      print("there is something wrong")
    finally:
      print("handling is over")
  ```
* raise는 throw와 같다. except는 catch와 같다. else는 default와 같다
* finally는 try-except가 끝이난 뒤, defer와 같은 동작이 필요할 때 사용된다
* `raise CriticalError from error` 처럼 원형이 되는 에러를 캐스팅하여 다른 에어를 던질 수 있다. 별로 의미있어 보이진 않는데 일단... 있다


<br>


### Class, scope
* 파이썬에서는 클래스의 property, method를 아울러 attribute라 한다
* init이라는 키워드는 따로 존재하지 않고, `def \_\_init\_\_(self, arguments...)`를 통해 이니셜라이저를 정의할 수 있다
* 스코프에 따라 nonlocal, global등의 키워드를 통해 해당 스코프의 값에 접근할 수 있는데,
* nonlocal은 뭔지 잘 모르겠네. 프로퍼티인가? 일단 패스
  ```python
    class SubClass(SuperClass):
      def \_\_init\_\_(self, arg1, arg2, arg3):
        self.a = arg1
        self.b = arg2
        self.c = arg3

      def deleteA:
        nonlocal a
        del a
        print(self.a) # error
  ```
* 클래스의 정의할 때, 인자로 상속받을 클래스를 넣어줄 수 있다. 상속이 필요없다면 ()를 생략할 수 있다
* 파이썬은 다중상속도 된다.
  ```python
    class SubClass(SuperClass1, SuperClass2, SuperClass3):
      pass
  ```
* 이건 좀 아닌 것 같은데... 잘 모르겠다
* 파이썬은 접근제어자가 따로 없는데, \_\_name\_\_처럼 __를 붙이는 경우에는 외부에서 바로 접근이 안되도록 숨겨준다고 한다
* 클래스의 인스턴스는 모두 루프를 돌릴 수 있는데, `iter()`와 `next()`를 사용하여 iterator를 만들고 사용할 수 있다
* 이때 \_\_iter\_\_, \_\_next\_\_를 정의하여 이를 커스터마이징 할 수도 있다
  * 딴 소린데 파이썬 __랑 마크다운 볼드랑 겹쳐서 쓸때마다 이스케이핑 해줘야하는 거 살짝 짜증나네...
* 


<br>


### 참고 문서

[파이썬 자습서 - 에러와 예외](https://docs.python.org/ko/3/tutorial/errors.html)

[파이썬 자습서 - 클래스](https://docs.python.org/ko/3/tutorial/classes.html)


내일이랑 모레 3개씩 보면 끝이네
